### ISSUE TITLE
issue with cbc

### ISSUE THREAD

**Issue by jdavid54** [yongtwang/engineering-python#2]
status = prob.solve()  # Solve with the default solver cbc
yields error on my raspberry pi :
OSError: [Errno 8] Exec format error: '/home/pi/.local/lib/python3.7/site-packages/pulp/apis/../solverdir/cbc/linux/32/cbc' 

Fixed the issue by replacing with GLPK :
status = prob.solve(GLPK_CMD(msg = 0))

**Comment by yongtwang** [comment]
Thank you for the solution on Raspberry Pi. The original file still works on Windows 11 PuLP-2.7.0.
